spring.application.name=admin-server

server.port=8085

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# --- Microservices a lancer automatiquement (dans l'ordre) ---
launcher.services[0].name=service-registry
launcher.services[0].path=../service-registry
launcher.services[0].port=8761
launcher.services[0].timeout-seconds=120

launcher.services[1].name=utilisateur-service
launcher.services[1].path=../utilisateur-service
launcher.services[1].port=8082
launcher.services[1].timeout-seconds=120

launcher.services[2].name=sujet-service
launcher.services[2].path=../sujet-service
launcher.services[2].port=8081
launcher.services[2].timeout-seconds=120

launcher.services[3].name=categorie-service
launcher.services[3].path=../categorie-service
launcher.services[3].port=8083
launcher.services[3].timeout-seconds=120

launcher.services[4].name=colonne-service
launcher.services[4].path=../colonne-service
launcher.services[4].port=8084
launcher.services[4].timeout-seconds=120

launcher.services[5].name=tier-liste-service
launcher.services[5].path=../tier-liste-service
launcher.services[5].port=8086
launcher.services[5].timeout-seconds=120

eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1
