spring.application.name=tier-liste-service

server.port=8086

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.generate_statistics=true
spring.jpa.properties.hibernate.session.events.log.LOG_QUERIES_SLOWER_THAN_MS=100

spring.datasource.url=jdbc:h2:~/tier_liste_service;AUTO_SERVER=TRUE
spring.jpa.hibernate.ddl-auto=create-drop

logging.level.org.hibernate.orm.jdbc.bind=trace

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=when-authorized

springdoc.swagger-ui.try-it-out-enabled=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.jpa.properties.hibernate.javax.cache.provider=org.ehcache.jsr107.EhcacheCachingProvider
spring.cache.jcache.provider=org.ehcache.jsr107.EhcacheCachingProvider

eureka.instance.prefer-ip-address=true
spring.cloud.inetutils.preferred-networks=192.168
