spring.application.name=sujet-service

server.port=8081

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.jpa.show-sql=true

spring.datasource.url=jdbc:h2:~/sujet;AUTO_SERVER=TRUE
spring.jpa.hibernate.ddl-auto=create-drop

spring.jpa.properties.hibernate.generate_statistics=true

spring.jpa.properties.hibernate.cache.use_query_cache=true

logging.level.org.hibernate.orm.jdbc.bind=trace
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.hibernate.session.events.log.LOG_QUERIES_SLOWER_THAN_MS=100

springdoc.swagger-ui.try-it-out-enabled=true

exemple=1234

eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1
eureka.instance.hostname=127.0.0.1

#---
spring.config.activate.on-profile=renfort
server.port=8480
spring.jpa.properties.hibernate.javax.cache.provider=org.ehcache.jsr107.EhcacheCachingProvider
spring.cache.jcache.provider=org.ehcache.jsr107.EhcacheCachingProvider
